# Generated by Django 5.1.3 on 2024-11-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appgest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="numero",
            field=models.CharField(
                blank=True, default="0151606704", max_length=25, null=True
            ),
        ),
    ]
