# Generated by Django 5.1.3 on 2024-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appgest", "0002_customuser_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bienimobilier",
            name="nommbre_chambre",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
