# Generated by Django 5.1.3 on 2024-11-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appgest", "0002_alter_customuser_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="numero",
        ),
    ]
