# Generated by Django 5.1.3 on 2024-11-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appgest", "0003_remove_customuser_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="BienImobilier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_bien",
                    models.CharField(
                        choices=[
                            ("maison", "Maison"),
                            ("appartement", "Appartement"),
                            ("terrain", "Terrain"),
                            ("locatif", "Locatif"),
                        ],
                        max_length=100,
                    ),
                ),
                ("adresse", models.CharField(max_length=255)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=10)),
                ("proprietaire", models.CharField(max_length=100)),
                ("date_acquisition", models.DateField()),
                ("date_chambre", models.IntegerField()),
                ("nbr_hectare", models.FloatField()),
                ("photo1", models.ImageField(upload_to="photo/")),
                ("photo3", models.ImageField(upload_to="photo/")),
                ("photo4", models.ImageField(upload_to="photo/")),
            ],
        ),
    ]
