# Generated by Django 5.1.3 on 2024-11-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appgest", "0004_bienimobilier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="est agent",
            new_name="is_agent",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="est contribuable",
            new_name="is_contribuable",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="Commune",
        ),
        migrations.AddField(
            model_name="bienimobilier",
            name="commune",
            field=models.CharField(
                choices=[
                    ("abobo", "Abobo"),
                    ("adjame", "Adjamé"),
                    ("attecoube", "Attécoubé"),
                    ("cocody", "Cocody"),
                    ("koumassi", "Koumassi"),
                    ("plateau", "Le Plateau"),
                    ("port-bouet", "Port-Bouët"),
                    ("san-pedro", "San-Pédro"),
                    ("treichville", "Treichville"),
                    ("yopougon", "Yopougon"),
                    ("batisse", "Bâtisse"),
                    ("anyama", "Anyama"),
                    ("grand-bassam", "Grand-Bassam"),
                    ("dabou", "Dabou"),
                    ("grand-lahou", "Grand-Lahou"),
                    ("agboville", "Agboville"),
                ],
                default="abobo",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="commune",
            field=models.CharField(
                choices=[
                    ("abobo", "Abobo"),
                    ("adjame", "Adjamé"),
                    ("attecoube", "Attécoubé"),
                    ("cocody", "Cocody"),
                    ("koumassi", "Koumassi"),
                    ("plateau", "Le Plateau"),
                    ("port-bouet", "Port-Bouët"),
                    ("san-pedro", "San-Pédro"),
                    ("treichville", "Treichville"),
                    ("yopougon", "Yopougon"),
                    ("batisse", "Bâtisse"),
                    ("anyama", "Anyama"),
                    ("grand-bassam", "Grand-Bassam"),
                    ("dabou", "Dabou"),
                    ("grand-lahou", "Grand-Lahou"),
                    ("agboville", "Agboville"),
                ],
                default=False,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
