# Generated by Django 5.1.3 on 2024-11-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appgest", "0006_bienimobilier_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bienimobilier",
            old_name="date_chambre",
            new_name="nommbre_chambre",
        ),
        migrations.RenameField(
            model_name="bienimobilier",
            old_name="photo4",
            new_name="photo2",
        ),
    ]
